### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [emavgl/oinkoin#43]
1.0.30 still has an old flutter: https://github.com/emavgl/oinkoin/tree/1.0.30/submodules

1.0.31 same: https://github.com/emavgl/oinkoin/tree/1.0.31/submodules

1.0.31 has no bumped version info either:  https://github.com/emavgl/oinkoin/blob/1.0.31/pubspec.yaml#L14

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/d8b690cddab43313eb28f0252a27afbb5eb91688

**Comment by emavgl** [comment]
Hi, thanks for the PR. Will revert to the older version soon.

Can you link me to the problem to the build?

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/d8b690cddab43313eb28f0252a27afbb5eb91688 - that's another problem. At the moment the tag is set, then the Github actions runs and commit the new version bump on the repo. Is this a problem with F-droid? I'll figure out a solution otherwise.

**Comment by licaon-kter** [comment]
Ah, forgot the link, here: https://gitlab.com/fdroid/fdroiddata/-/jobs/5772369823#L1122

**Comment by emavgl** [comment]
Hi @licaon-kter,

It should be fixed. I upgraded the dart sdk version. However, I have tried running it locally at failed with

```
 ERROR: Unused scanignore path: submodules/flutter/packages/flutter_tools/gradle/flutter.gradle
```

Not sure if it is a problem with my local setup.

I am using this configuration

```
Builds:
  - versionName: 1.0.31
    versionCode: 8025
    commit: 121896fcd65f162b33977db8db100a95d19bcf1b
    submodules: true
    output: build/app/outputs/flutter-apk/app-arm64-v8a-fdroid-release.apk
    rm:
      - ios
      - macos
    prebuild:
      - export PUB_CACHE=$(pwd)/.pub-cache
      - submodules/flutter/bin/flutter config --no-analytics
      - submodules/flutter/bin/flutter pub get
    scanignore:
      - submodules/flutter/packages/flutter_tools/gradle/flutter.gradle
      - submodules/flutter/bin/cache
    scandelete:
      - submodules/flutter
      - .pub-cache
    build:
      - export PUB_CACHE=$(pwd)/.pub-cache
      - submodules/flutter/bin/flutter build apk --release --flavor fdroid --split-per-abi
        --target-platform="android-arm64"

AutoUpdateMode: Version
UpdateCheckMode: Tags
VercodeOperation:
  - 2 * 1000 + %c
UpdateCheckData: pubspec.yaml|version:\s.+\+(\d+)|.|version:\s(.+)\+
CurrentVersion: 1.0.31
CurrentVersionCode: 8025
```
